# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details
import os
from typing import Any

from ecoscope.platform.tasks.config import set_workflow_details as set_workflow_details
from ecoscope.platform.tasks.filter import set_time_range as set_time_range
from ecoscope.platform.tasks.io import (
    get_spatial_features_group as get_spatial_features_group,
)
from ecoscope.platform.tasks.io import (
    get_subjectgroup_observations as get_subjectgroup_observations,
)
from ecoscope.platform.tasks.io import persist_text as persist_text
from ecoscope.platform.tasks.io import set_er_connection as set_er_connection
from ecoscope.platform.tasks.results import (
    create_map_widget_single_view as create_map_widget_single_view,
)
from ecoscope.platform.tasks.results import create_polygon_layer as create_polygon_layer
from ecoscope.platform.tasks.results import (
    create_single_value_widget_single_view as create_single_value_widget_single_view,
)
from ecoscope.platform.tasks.results import (
    create_text_widget_single_view as create_text_widget_single_view,
)
from ecoscope.platform.tasks.results import draw_ecomap as draw_ecomap
from ecoscope.platform.tasks.results import gather_dashboard as gather_dashboard
from ecoscope.platform.tasks.results import set_base_maps as set_base_maps
from ecoscope.platform.tasks.skip import all_geometry_are_none as all_geometry_are_none
from ecoscope.platform.tasks.skip import (
    any_dependency_is_empty_string as any_dependency_is_empty_string,
)
from ecoscope.platform.tasks.skip import (
    any_dependency_skipped as any_dependency_skipped,
)
from ecoscope.platform.tasks.skip import any_is_empty_df as any_is_empty_df
from ecoscope.platform.tasks.skip import never as never
from ecoscope.platform.tasks.transformation import apply_color_map as apply_color_map
from hex_tasks import classify_hex_bins as classify_hex_bins
from hex_tasks import combine_map_layers as combine_map_layers
from hex_tasks import count_hexbins as count_hexbins
from hex_tasks import count_observations as count_observations
from hex_tasks import count_subjects as count_subjects
from hex_tasks import create_hex_polygon_layer as create_hex_polygon_layer
from hex_tasks import create_overlay_layer as create_overlay_layer
from hex_tasks import export_geodataframe as export_geodataframe
from hex_tasks import format_h3_resolution as format_h3_resolution
from hex_tasks import format_optional_name as format_optional_name
from hex_tasks import hex_bin_observations as hex_bin_observations
from hex_tasks import normalize_boundary_geometry as normalize_boundary_geometry
from hex_tasks import set_boundary_group_name as set_boundary_group_name
from hex_tasks import set_colormap as set_colormap
from hex_tasks import set_h3_resolution as set_h3_resolution
from hex_tasks import set_overlay_group_name as set_overlay_group_name
from hex_tasks import set_subject_group_name as set_subject_group_name
from wt_contracts import validate as _validate
from wt_task import task

from .. import metadata as _metadata


def main(params: dict[str, Any], validate_params_schema: bool = True):
    if validate_params_schema:
        _validate(params, _metadata.load_params_schema())

    workflow_details = (
        task(set_workflow_details)
        .validate()
        .set_task_instance_id("workflow_details")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("workflow_details") or {}))
        .call()
    )

    er_client_name = (
        task(set_er_connection)
        .validate()
        .set_task_instance_id("er_client_name")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("er_client_name") or {}))
        .call()
    )

    time_range = (
        task(set_time_range)
        .validate()
        .set_task_instance_id("time_range")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(time_format="%d %b %Y %H:%M:%S", **(params.get("time_range") or {}))
        .call()
    )

    subject_group = (
        task(set_subject_group_name)
        .validate()
        .set_task_instance_id("subject_group")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("subject_group") or {}))
        .call()
    )

    get_observations = (
        task(get_subjectgroup_observations)
        .validate()
        .set_task_instance_id("get_observations")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            client=er_client_name,
            time_range=time_range,
            subject_group_name=subject_group,
            raise_on_empty=True,
            include_details=False,
            include_subjectsource_details=False,
            filter="clean",
            **(params.get("get_observations") or {}),
        )
        .call()
    )

    boundary_name = (
        task(set_boundary_group_name)
        .validate()
        .set_task_instance_id("boundary_name")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("boundary_name") or {}))
        .call()
    )

    overlay_name = (
        task(set_overlay_group_name)
        .validate()
        .set_task_instance_id("overlay_name")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("overlay_name") or {}))
        .call()
    )

    boundary_features = (
        task(get_spatial_features_group)
        .validate()
        .set_task_instance_id("boundary_features")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_dependency_is_empty_string,
            ],
            unpack_depth=1,
        )
        .partial(
            client=er_client_name,
            spatial_features_group_name=boundary_name,
            **(params.get("boundary_features") or {}),
        )
        .call()
    )

    overlay_features = (
        task(get_spatial_features_group)
        .validate()
        .set_task_instance_id("overlay_features")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_dependency_is_empty_string,
            ],
            unpack_depth=1,
        )
        .partial(
            client=er_client_name,
            spatial_features_group_name=overlay_name,
            **(params.get("overlay_features") or {}),
        )
        .call()
    )

    colormap_picker = (
        task(set_colormap)
        .validate()
        .set_task_instance_id("colormap_picker")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("colormap_picker") or {}))
        .call()
    )

    base_maps = (
        task(set_base_maps)
        .validate()
        .set_task_instance_id("base_maps")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("base_maps") or {}))
        .call()
    )

    h3_resolution = (
        task(set_h3_resolution)
        .validate()
        .set_task_instance_id("h3_resolution")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("h3_resolution") or {}))
        .call()
    )

    hex_bins = (
        task(hex_bin_observations)
        .validate()
        .set_task_instance_id("hex_bins")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                all_geometry_are_none,
            ],
            unpack_depth=1,
        )
        .partial(
            geodataframe=get_observations,
            boundary=boundary_features,
            h3_resolution=h3_resolution,
            count_column="count",
            **(params.get("hex_bins") or {}),
        )
        .call()
    )

    classify_counts = (
        task(classify_hex_bins)
        .validate()
        .set_task_instance_id("classify_counts")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(geodataframe=hex_bins, **(params.get("classify_counts") or {}))
        .call()
    )

    hex_colormap = (
        task(apply_color_map)
        .validate()
        .set_task_instance_id("hex_colormap")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=classify_counts,
            input_column_name="count_class",
            output_column_name="count_colors",
            colormap=colormap_picker,
            **(params.get("hex_colormap") or {}),
        )
        .call()
    )

    hex_layer = (
        task(create_hex_polygon_layer)
        .validate()
        .set_task_instance_id("hex_layer")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
                all_geometry_are_none,
            ],
            unpack_depth=1,
        )
        .partial(
            geodataframe=hex_colormap,
            fill_color_column="count_colors",
            label_column="count_range",
            get_line_width=1.0,
            opacity=0.9,
            tooltip_columns=["count"],
            **(params.get("hex_layer") or {}),
        )
        .call()
    )

    boundary_polygon = (
        task(normalize_boundary_geometry)
        .validate()
        .set_task_instance_id("boundary_polygon")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_dependency_skipped,
                any_is_empty_df,
            ],
            unpack_depth=1,
        )
        .partial(
            geodataframe=boundary_features, **(params.get("boundary_polygon") or {})
        )
        .call()
    )

    boundary_layer = (
        task(create_polygon_layer)
        .validate()
        .set_task_instance_id("boundary_layer")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_dependency_skipped,
                any_is_empty_df,
            ],
            unpack_depth=1,
        )
        .partial(
            geodataframe=boundary_polygon,
            legend=None,
            tooltip_columns=[],
            layer_style={
                "filled": False,
                "stroked": True,
                "get_line_color": "#FFFFFF",
                "get_line_width": 3,
                "line_width_units": "pixels",
            },
            **(params.get("boundary_layer") or {}),
        )
        .call()
    )

    overlay_layer = (
        task(create_overlay_layer)
        .validate()
        .set_task_instance_id("overlay_layer")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_dependency_skipped,
                any_is_empty_df,
            ],
            unpack_depth=1,
        )
        .partial(
            geodataframe=overlay_features,
            get_color="#FF8C00",
            get_width=2.0,
            **(params.get("overlay_layer") or {}),
        )
        .call()
    )

    combined_layers = (
        task(combine_map_layers)
        .validate()
        .set_task_instance_id("combined_layers")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
            ],
            unpack_depth=1,
        )
        .partial(
            hex_layer=hex_layer,
            boundary_layer=boundary_layer,
            overlay_layer=overlay_layer,
            **(params.get("combined_layers") or {}),
        )
        .call()
    )

    hexgrid_map = (
        task(draw_ecomap)
        .validate()
        .set_task_instance_id("hexgrid_map")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            title=None,
            tile_layers=base_maps,
            north_arrow_style={"placement": "top-left"},
            legend_style={"title": "Fix Count", "placement": "bottom-right"},
            static=False,
            max_zoom=20,
            geo_layers=combined_layers,
            **(params.get("hexgrid_map") or {}),
        )
        .call()
    )

    hexgrid_map_url = (
        task(persist_text)
        .validate()
        .set_task_instance_id("hexgrid_map_url")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="hexgrid",
            text=hexgrid_map,
            **(params.get("hexgrid_map_url") or {}),
        )
        .call()
    )

    export_hex_bins = (
        task(export_geodataframe)
        .validate()
        .set_task_instance_id("export_hex_bins")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            geodataframe=hex_colormap,
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="hexgrid_hexbins",
            layer_name="hexgrid",
            **(params.get("export_hex_bins") or {}),
        )
        .call()
    )

    stat_fixes = (
        task(count_observations)
        .validate()
        .set_task_instance_id("stat_fixes")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
            ],
            unpack_depth=1,
        )
        .partial(geodataframe=get_observations, **(params.get("stat_fixes") or {}))
        .call()
    )

    stat_subjects = (
        task(count_subjects)
        .validate()
        .set_task_instance_id("stat_subjects")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
            ],
            unpack_depth=1,
        )
        .partial(geodataframe=get_observations, **(params.get("stat_subjects") or {}))
        .call()
    )

    stat_hexbins = (
        task(count_hexbins)
        .validate()
        .set_task_instance_id("stat_hexbins")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(geodataframe=hex_colormap, **(params.get("stat_hexbins") or {}))
        .call()
    )

    h3_resolution_label = (
        task(format_h3_resolution)
        .validate()
        .set_task_instance_id("h3_resolution_label")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[],
            unpack_depth=1,
        )
        .partial(
            h3_resolution=h3_resolution, **(params.get("h3_resolution_label") or {})
        )
        .call()
    )

    widget_fixes = (
        task(create_single_value_widget_single_view)
        .validate()
        .set_task_instance_id("widget_fixes")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Total Locations",
            data=stat_fixes,
            decimal_places=0,
            **(params.get("widget_fixes") or {}),
        )
        .call()
    )

    widget_subjects = (
        task(create_single_value_widget_single_view)
        .validate()
        .set_task_instance_id("widget_subjects")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Subjects Tracked",
            data=stat_subjects,
            decimal_places=0,
            **(params.get("widget_subjects") or {}),
        )
        .call()
    )

    widget_hexbins = (
        task(create_single_value_widget_single_view)
        .validate()
        .set_task_instance_id("widget_hexbins")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Active Hexbins",
            data=stat_hexbins,
            decimal_places=0,
            **(params.get("widget_hexbins") or {}),
        )
        .call()
    )

    widget_h3_resolution = (
        task(create_text_widget_single_view)
        .validate()
        .set_task_instance_id("widget_h3_resolution")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Resolution",
            data=h3_resolution_label,
            **(params.get("widget_h3_resolution") or {}),
        )
        .call()
    )

    stat_boundary_fmt = (
        task(format_optional_name)
        .validate()
        .set_task_instance_id("stat_boundary_fmt")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[],
            unpack_depth=1,
        )
        .partial(name=boundary_name, **(params.get("stat_boundary_fmt") or {}))
        .call()
    )

    stat_overlay_fmt = (
        task(format_optional_name)
        .validate()
        .set_task_instance_id("stat_overlay_fmt")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[],
            unpack_depth=1,
        )
        .partial(name=overlay_name, **(params.get("stat_overlay_fmt") or {}))
        .call()
    )

    widget_subject_group = (
        task(create_text_widget_single_view)
        .validate()
        .set_task_instance_id("widget_subject_group")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Group",
            data=subject_group,
            **(params.get("widget_subject_group") or {}),
        )
        .call()
    )

    widget_boundary = (
        task(create_text_widget_single_view)
        .validate()
        .set_task_instance_id("widget_boundary")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Boundary",
            data=stat_boundary_fmt,
            **(params.get("widget_boundary") or {}),
        )
        .call()
    )

    widget_overlay = (
        task(create_text_widget_single_view)
        .validate()
        .set_task_instance_id("widget_overlay")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Overlay",
            data=stat_overlay_fmt,
            **(params.get("widget_overlay") or {}),
        )
        .call()
    )

    map_widget = (
        task(create_map_widget_single_view)
        .validate()
        .set_task_instance_id("map_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Subject Hexgrid Map",
            data=hexgrid_map_url,
            **(params.get("map_widget") or {}),
        )
        .call()
    )

    dashboard = (
        task(gather_dashboard)
        .validate()
        .set_task_instance_id("dashboard")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            details=workflow_details,
            widgets=[
                widget_fixes,
                widget_subjects,
                widget_hexbins,
                widget_h3_resolution,
                widget_subject_group,
                widget_boundary,
                widget_overlay,
                map_widget,
            ],
            time_range=time_range,
            **(params.get("dashboard") or {}),
        )
        .call()
    )

    return dashboard
